// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'editResult': string;
  'editorPane': string;
  'editorWrapper': string;
  'markdown': string;
}
export const cssExports: CssExports;
export default cssExports;
