// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'editArticle': string;
  'editor': string;
  'header': string;
  'label': string;
  'newTagBtn': string;
  'setInfo': string;
  'tags': string;
  'titleInput': string;
}
export const cssExports: CssExports;
export default cssExports;
